import { describe, expect, it } from "vitest";
import { MELODY_AUDIT_COUNTS, melodyAuditCounts } from "./melodyAudit";

const part = { file: "a.ly", target: "part:x/introit", hash: "render-a" };
const auditItem = {
  file: "a.ly", target: "part:x/introit", hash: "render-a", chant_id: 7,
  gabc_hash: "gabc-a", status: "melody-agrees",
};

describe("melody audit counts", () => {
  it("matches the checked-in current evidence snapshot", () => {
    expect(MELODY_AUDIT_COUNTS).toMatchObject({ checked: 747, agreement: 70 });
  });

  it("counts only evidence matching the current render and reference GABC", () => {
    const result = melodyAuditCounts(
      [part, { ...part, file: "b.ly", hash: "render-b" }],
      {},
      { items: [auditItem, { ...auditItem, file: "b.ly", hash: "old", status: "melody-differs" }] },
      new Map([["part:x/introit", { id: 7, gabcHash: "gabc-a" }]]),
    );
    expect(result).toEqual({ remaining: 2, checked: 1, agreement: 1, attention: 0, noReference: 0, unchecked: 1 });
  });

  it("keeps current no-reference rows valid only while the catalogue has no GABC", () => {
    const result = melodyAuditCounts(
      [part, { ...part, file: "b.ly", target: "part:x/gradual", hash: "render-b" }], {},
      { items: [{ file: "a.ly", target: "part:x/introit", hash: "render-a", chant_id: null, status: "no-reference" }] },
      new Map([["part:x/introit", { id: null, gabcHash: null }]]),
    );
    expect(result).toEqual({ remaining: 2, checked: 1, agreement: 0, attention: 0, noReference: 1, unchecked: 1 });
  });

  it("excludes reviewed current renders and counts valid discrepancies as attention", () => {
    const result = melodyAuditCounts(
      [part, { ...part, file: "b.ly", target: "part:x/gradual", hash: "render-b" }],
      { "typeset:a.ly": { was: "render-a" } },
      { items: [{ ...auditItem, file: "b.ly", target: "part:x/gradual", hash: "render-b", chant_id: 9, gabc_hash: "gabc-z", status: "melody-differs" }] },
      new Map([["part:x/gradual", { id: 9, gabcHash: "gabc-z" }]]),
    );
    expect(result).toEqual({ remaining: 1, checked: 1, agreement: 0, attention: 1, noReference: 0, unchecked: 0 });
  });

  it("ignores evidence generated by a different audit algorithm", () => {
    const result = melodyAuditCounts([part], {}, { algorithm: "melody-audit-0", items: [auditItem] },
      new Map([["part:x/introit", { id: 7, gabcHash: "gabc-a" }]]), "current-source-hash");
    expect(result).toEqual({ remaining: 1, checked: 0, agreement: 0, attention: 0, noReference: 0, unchecked: 1 });
  });

  it("ignores evidence when its implementation hash is stale", () => {
    const result = melodyAuditCounts([part], {},
      { algorithm: "melody-audit-1", algorithm_hash: "old-source-hash", items: [auditItem] },
      new Map([["part:x/introit", { id: 7, gabcHash: "gabc-a" }]]), "current-source-hash");
    expect(result).toEqual({ remaining: 1, checked: 0, agreement: 0, attention: 0, noReference: 0, unchecked: 1 });
  });
});
